version: '2'
services:
  tests:
    image: "${DOCKER_REPOSITORY}:${COMMIT}"
    environment:
      - NPM_USER
      - NPM_PASS
      - NPM_EMAIL
      - AWS_KEY
      - AWS_SECRET
      - BUILDKITE_MESSAGE
      - JEFFREY_TOKEN_staging
      - BUCKET_staging
      - BUCKET_PREFIX_staging
      - AWS_KEY_staging
      - AWS_SECRET_staging
      - JEFFREY_TOKEN_production
      - BUCKET_production
      - BUCKET_PREFIX_production
      - AWS_KEY_production
      - AWS_SECRET_production
